project:
  type: website
  output-dir: _site
format:
  html:
    theme: litera
    toc: true
    toc-location: right
    self-contained: true
website:
  title: "Data I/O 2025"
  site-url: https://dataio-2025.netlify.app
  repo-url: https://github.com/SadeekFarhan21/dataio-2025
  navbar:
    left:
      - text: "About Us"
        href: about.qmd
      - ragav.qmd
      - luke.qmd
      - jayson.qmd